"""Validate that commits in a range follow Conventional Commits — for CI gating."""

from __future__ import annotations

from dataclasses import dataclass

from .git import RawCommit, get_raw_commits
from .parser import parse_commit


@dataclass(frozen=True)
class Violation:
    sha: str
    subject: str


def _is_checked(commit: RawCommit) -> bool:
    return not commit.is_merge


def lint(rev_range: str, repo_path: str = ".") -> list[Violation]:
    """Return commits in `rev_range` that don't follow Conventional Commits.

    Merge commits are exempt since their subjects are generated by git, not authored.
    """
    violations: list[Violation] = []
    for commit in get_raw_commits(rev_range, repo_path):
        if not _is_checked(commit):
            continue
        if parse_commit(commit.sha, commit.subject, commit.body) is None:
            violations.append(Violation(sha=commit.sha, subject=commit.subject))
    return violations
